-- Script simple para crear un artículo de prueba en Supabase
-- Ejecutar en el SQL Editor de Supabase

INSERT INTO blog_articles (
  title,
  subtitle,
  slug,
  excerpt,
  introduction,
  psychological_analysis,
  practical_recommendations,
  category,
  tags,
  author_name,
  author_credentials,
  reading_time_minutes,
  status,
  review_status,
  published_at,
  is_featured,
  is_trending,
  is_professional_content,
  view_count,
  likes_count,
  shares_count,
  comments_enabled,
  professional_feedback_enabled,
  topic_complexity
) VALUES (
  '¿Cómo ayudar a tu hijo con la ansiedad escolar?',
  'Estrategias prácticas para padres y madres',
  'ansiedad-escolar-ayuda-hijos',
  'La ansiedad escolar es un problema común que afecta a muchos niños. En este artículo te damos herramientas prácticas para ayudar a tu hijo.',
  'La vuelta al colegio puede ser un momento de alegría para algunos niños, pero para otros puede convertirse en una fuente de ansiedad y estrés. Como padres, es importante reconocer las señales y saber cómo actuar.',
  'La ansiedad escolar puede manifestarse de diferentes formas: dolores de estómago, dificultades para dormir, llanto o resistencia a ir al colegio. Desde el punto de vista psicológico, es importante entender que esta ansiedad es una respuesta natural del sistema nervioso ante una situación percibida como amenazante.',
  ARRAY[
    'Establece rutinas predecibles antes y después del colegio',
    'Practica técnicas de respiración profunda con tu hijo',
    'Comunícate regularmente con los profesores',
    'Valida los sentimientos de tu hijo sin minimizar su experiencia',
    'Considera la ayuda de un profesional si la ansiedad persiste'
  ],
  'emociones',
  ARRAY['ansiedad', 'escuela', 'niños', 'padres', 'estrategias'],
  'Llenia Monteagudo',
  'Psicóloga Infantil Colegiada',
  7,
  'published',
  'approved',
  NOW(),
  true,
  false,
  true,
  0,
  0,
  0,
  true,
  true,
  'beginner'
);